package com.proxyplatform.app

/**
 * Preset data adapted from Ackites/Nrfr (Apache-2.0); see assets/licenses/NRFR-LICENSE.txt.
 * Country and carrier choices are retained; labels are localized for this app.
 */
internal data class SimCountryPreset(val code: String, val label: String)

internal data class SimCarrierPreset(
    val id: String,
    val label: String,
    val displayName: String,
    val region: String,
    val custom: Boolean = false,
)

internal object SimNrfrPresets {
    val countries = listOf(
        SimCountryPreset("CN", "الصين"),
        SimCountryPreset("HK", "هونغ كونغ"),
        SimCountryPreset("MO", "ماكاو"),
        SimCountryPreset("TW", "تايوان"),
        SimCountryPreset("JP", "اليابان"),
        SimCountryPreset("KR", "كوريا الجنوبية"),
        SimCountryPreset("US", "الولايات المتحدة"),
        SimCountryPreset("GB", "المملكة المتحدة"),
        SimCountryPreset("DE", "ألمانيا"),
        SimCountryPreset("FR", "فرنسا"),
        SimCountryPreset("IT", "إيطاليا"),
        SimCountryPreset("ES", "إسبانيا"),
        SimCountryPreset("PT", "البرتغال"),
        SimCountryPreset("RU", "روسيا"),
        SimCountryPreset("IN", "الهند"),
        SimCountryPreset("AU", "أستراليا"),
        SimCountryPreset("NZ", "نيوزيلندا"),
        SimCountryPreset("SG", "سنغافورة"),
        SimCountryPreset("MY", "ماليزيا"),
        SimCountryPreset("TH", "تايلاند"),
        SimCountryPreset("VN", "فيتنام"),
        SimCountryPreset("ID", "إندونيسيا"),
        SimCountryPreset("PH", "الفلبين"),
        SimCountryPreset("CA", "كندا"),
        SimCountryPreset("MX", "المكسيك"),
        SimCountryPreset("BR", "البرازيل"),
        SimCountryPreset("AR", "الأرجنتين"),
        SimCountryPreset("ZA", "جنوب أفريقيا"),
    ).sortedBy { it.label }

    val carriers = listOf(
        SimCarrierPreset("cn_cmcc", "China Mobile", "China Mobile", "CN"),
        SimCarrierPreset("cn_cucc", "China Unicom", "China Unicom", "CN"),
        SimCarrierPreset("cn_ct", "China Telecom", "China Telecom", "CN"),
        SimCarrierPreset("hk_cmhk", "CMHK", "CMHK", "HK"),
        SimCarrierPreset("hk_hkt", "HKT", "HKT", "HK"),
        SimCarrierPreset("hk_3", "3HK", "3HK", "HK"),
        SimCarrierPreset("hk_smartone", "SmarTone", "SmarTone", "HK"),
        SimCarrierPreset("mo_ctm", "CTM", "CTM", "MO"),
        SimCarrierPreset("mo_3", "3 Macau", "3 Macau", "MO"),
        SimCarrierPreset("tw_chunghwa", "Chunghwa Telecom", "Chunghwa Telecom", "TW"),
        SimCarrierPreset("tw_taiwan_mobile", "Taiwan Mobile", "Taiwan Mobile", "TW"),
        SimCarrierPreset("tw_fareastone", "FarEasTone", "FarEasTone", "TW"),
        SimCarrierPreset("jp_docomo", "NTT docomo", "NTT docomo", "JP"),
        SimCarrierPreset("jp_au", "au", "au by KDDI", "JP"),
        SimCarrierPreset("jp_softbank", "Softbank", "Softbank", "JP"),
        SimCarrierPreset("jp_rakuten", "Rakuten", "Rakuten Mobile", "JP"),
        SimCarrierPreset("kr_skt", "SK Telecom", "SK Telecom", "KR"),
        SimCarrierPreset("kr_kt", "KT", "KT Corporation", "KR"),
        SimCarrierPreset("kr_lgu", "LG U+", "LG U+", "KR"),
        SimCarrierPreset("us_att", "AT&T", "AT&T", "US"),
        SimCarrierPreset("us_tmobile", "T-Mobile", "T-Mobile USA", "US"),
        SimCarrierPreset("us_verizon", "Verizon", "Verizon", "US"),
        SimCarrierPreset("us_sprint", "Sprint", "Sprint", "US"),
        SimCarrierPreset("gb_ee", "EE", "EE", "GB"),
        SimCarrierPreset("gb_o2", "O2", "O2 UK", "GB"),
        SimCarrierPreset("gb_three", "Three", "Three UK", "GB"),
        SimCarrierPreset("gb_vodafone", "Vodafone", "Vodafone UK", "GB"),
        SimCarrierPreset("sg_singtel", "Singtel", "Singtel", "SG"),
        SimCarrierPreset("sg_starhub", "StarHub", "StarHub", "SG"),
        SimCarrierPreset("sg_m1", "M1", "M1", "SG"),
        SimCarrierPreset("my_maxis", "Maxis", "Maxis", "MY"),
        SimCarrierPreset("my_celcom", "Celcom", "Celcom", "MY"),
        SimCarrierPreset("my_digi", "Digi", "Digi", "MY"),
        SimCarrierPreset("my_umobile", "U Mobile", "U Mobile", "MY"),
        SimCarrierPreset("th_ais", "AIS", "AIS", "TH"),
        SimCarrierPreset("th_dtac", "DTAC", "DTAC", "TH"),
        SimCarrierPreset("th_true", "True Move H", "True Move H", "TH"),
        SimCarrierPreset("vn_viettel", "Viettel", "Viettel Mobile", "VN"),
        SimCarrierPreset("vn_vina", "Vinaphone", "Vinaphone", "VN"),
        SimCarrierPreset("vn_mobi", "Mobifone", "Mobifone", "VN"),
        SimCarrierPreset("id_telkomsel", "Telkomsel", "Telkomsel", "ID"),
        SimCarrierPreset("id_indosat", "Indosat", "Indosat Ooredoo", "ID"),
        SimCarrierPreset("id_xl", "XL Axiata", "XL Axiata", "ID"),
        SimCarrierPreset("ph_globe", "Globe", "Globe Telecom", "PH"),
        SimCarrierPreset("ph_smart", "Smart", "Smart Communications", "PH"),
        SimCarrierPreset("ph_dito", "DITO", "DITO Telecommunity", "PH"),
        SimCarrierPreset("in_jio", "Jio", "Reliance Jio", "IN"),
        SimCarrierPreset("in_airtel", "Airtel", "Bharti Airtel", "IN"),
        SimCarrierPreset("in_vi", "Vi", "Vodafone Idea", "IN"),
        SimCarrierPreset("au_telstra", "Telstra", "Telstra", "AU"),
        SimCarrierPreset("au_optus", "Optus", "Optus", "AU"),
        SimCarrierPreset("au_vodafone", "Vodafone", "Vodafone AU", "AU"),
        SimCarrierPreset("ca_bell", "Bell", "Bell Mobility", "CA"),
        SimCarrierPreset("ca_rogers", "Rogers", "Rogers Wireless", "CA"),
        SimCarrierPreset("ca_telus", "Telus", "Telus Mobility", "CA"),
        SimCarrierPreset("de_telekom", "Telekom", "T-Mobile DE", "DE"),
        SimCarrierPreset("de_vodafone", "Vodafone", "Vodafone DE", "DE"),
        SimCarrierPreset("de_o2", "O2", "O2 DE", "DE"),
        SimCarrierPreset("fr_orange", "Orange", "Orange FR", "FR"),
        SimCarrierPreset("fr_sfr", "SFR", "SFR", "FR"),
        SimCarrierPreset("fr_free", "Free", "Free Mobile", "FR"),
        SimCarrierPreset("fr_bouygues", "Bouygues", "Bouygues Telecom", "FR"),
        SimCarrierPreset("it_tim", "TIM", "Telecom Italia", "IT"),
        SimCarrierPreset("it_vodafone", "Vodafone", "Vodafone IT", "IT"),
        SimCarrierPreset("it_windtre", "Wind Tre", "Wind Tre", "IT"),
        SimCarrierPreset("es_movistar", "Movistar", "Movistar", "ES"),
        SimCarrierPreset("es_vodafone", "Vodafone", "Vodafone ES", "ES"),
        SimCarrierPreset("es_orange", "Orange", "Orange ES", "ES"),
        SimCarrierPreset("ru_mts", "MTS", "MTS", "RU"),
        SimCarrierPreset("ru_megafon", "MegaFon", "MegaFon", "RU"),
        SimCarrierPreset("ru_beeline", "Beeline", "Beeline", "RU"),
        SimCarrierPreset("br_vivo", "Vivo", "Vivo", "BR"),
        SimCarrierPreset("br_claro", "Claro", "Claro", "BR"),
        SimCarrierPreset("br_tim", "TIM", "TIM Brasil", "BR"),
        SimCarrierPreset("custom", "مخصص", "", "", custom = true),
    )
}
